#! /bin/sh

#----------------------#
# STARTUP APPLICATIONS #
#----------------------#

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/scripts/launch.sh

# Background
feh --bg-fill $HOME/Pictures/life.jpg &

# Add mouse cursor support 
xsetroot -cursor_name left_ptr &

# Screen color calibration
xcalib -d :0 $HOME/.config/icc/x200.icc

# Disable screen blanking
xset -dpms s off &

# Disable wi-fi
#sudo /sbin/ip link set wlan0 down &

# Disable eth
#sudo /sbin/ip link set enp1s0 down &

# Disable headphone/mic
pactl set-sink-mute @DEFAULT_SINK@ 1 &
pactl set-source-mute @DEFAULT_SOURCE@ 1 &


#--------#
# BASICS #
#--------#

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap         	 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#00bfff
bspc config normal_border_color  \#cccccc


#-------#
# RULES #
#-------#

bspc rule -a firefox                 desktop='^2' state=tiled follow=on
bspc rule -a URxvt:code              desktop='^3' state=tiled follow=on
bspc rule -a latex                   desktop='^4' state=tiled follow=on 
bspc rule -a Soffice                 desktop='^4' state=tiled follow=on
bspc rule -a libreoffice-startcenter desktop='^4' state=tiled follow=on
bspc rule -a Zathura 	     	         desktop='^4' state=tiled follow=off focus=off split_ratio=0.65
bspc rule -a TelegramDesktop 	       desktop='^5' state=tiled follow=on
bspc rule -a discord                 desktop='^5' state=tiled follow=on
bspc rule -a mpv                     desktop='^6' state=tiled follow=on
bspc rule -a Spotify                 desktop='^6' state=tiled follow=on
bspc rule -a Virt-manager            desktop='^7' state=tiled follow=on

bspc rule -a Iwgtk                state=floating center=true rectangle=900x500+0+0
bspc rule -a Blueman-manager      state=floating center=true rectangle=900x500+0+0
bspc rule -a Pavucontrol          state=floating center=true rectangle=900x500+0+0
bspc rule -a Sxiv                 state=floating center=true 
