#! /bin/sh

#--------#
# BASICS #
#--------#

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap         	 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#00bfff
bspc config normal_border_color  \#cccccc


#-------#
# RULES #
#-------#

bspc rule -a Firefox        	    desktop='^2' state=tiled follow=on
bspc rule -a "*:code"             desktop='^3' state=tiled follow=on
bspc rule -a "*:latex"            desktop='^4' state=tiled follow=on 
bspc rule -a Zathura 	     	      desktop='^4' state=tiled follow=on
bspc rule -a TelegramDesktop 	    desktop='^5' state=tiled follow=on
bspc rule -a discord              desktop='^5' state=tiled follow=on
bspc rule -a mpv                  desktop='^6' state=tiled follow=on
bspc rule -a Virt-manager         desktop='^7' state=tiled follow=on

#bspc rule -a Blueman-manager      state=floating center=true rectangle=900x500+0+0


#----------------------#
# STARTUP APPLICATIONS #
#----------------------#

# status bar
$HOME/.config/polybar/scripts/launch.sh

# change keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ru &

# Solid color background
xsetroot -solid "#cccccc" &

# Disable screen blanking
xset -dpms s off &

# Disable wi-fi
#sudo /sbin/ip link set wlan0 down &

# Disable eth
#sudo /sbin/ip link set enp1s0 down &

# Disable headphone/mic
amixer set Master mute
amixer set Capture 0%
