#! /bin/sh

#--------#
# BASICS #
#--------#

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap         	 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#00bfff
bspc config normal_border_color  \#cccccc

#----------------------#
# STARTUP APPLICATIONS #
#----------------------#

# status bar
$HOME/.config/polybar/scripts/launch.sh

# change keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ru &

# Solid color background
xsetroot -solid "#cccccc" &

# Disable screen blanking
xset -dpms s off &

# Network manager tray
nm-applet &
