#! /bin/sh

#----------------------#
# STARTUP APPLICATIONS #
#----------------------#

$HOME/.config/polybar/scripts/launch.sh

# Disable headphone/mic
pactl set-sink-mute @DEFAULT_SINK@ 1 &
pactl set-source-mute @DEFAULT_SOURCE@ 1 &

#polybar-msg cmd show
bspc config top_padding 18

#--------#
# BASICS #
#--------#

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap         	 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#00bfff
bspc config normal_border_color  \#cccccc


#-------#
# RULES #
#-------#

bspc rule -a Firefox                 desktop='^2' state=tiled follow=on
bspc rule -a code-oss                desktop='^3' state=tiled follow=on
bspc rule -a okular         	       desktop='^4' state=tiled follow=on
bspc rule -a DesktopEditors          desktop='^4' state=tiled follow=on
bspc rule -a TelegramDesktop 	       desktop='^5' state=tiled follow=on
bspc rule -a discord                 desktop='^5' state=tiled follow=on
bspc rule -a mpv                     desktop='^6' state=tiled follow=on
bspc rule -a VirtualBox              desktop='^7' state=tiled follow=on

bspc rule -a Iwgtk                state=floating center=true rectangle=900x500+0+0
bspc rule -a Blueman-manager    state=floating center=true rectangle=900x500+0+0
bspc rule -a Pavucontrol          state=floating center=true rectangle=900x500+0+0


bspc rule -a Emacs       state=tiled
bspc rule -a feh        state=floating 
bspc rule -a firefox:Firefox      state=floating 
bspc rule -a firefox:Places        state=floating
bspc rule -a VirtualBox:VirtualBox state=floating

